public enum Cities {
    Arkhangelsk,
    Stokgolm,
    Gdansk,
    Rotterdam,
    Edinburgh,
    Liverpool,
    Brest,
    Nantes,
    Bordeaux,
    Porto,
    Lisbon,
    valencia,
    marseille,
    genoa,
    tunisia,
    venice,
    athens,
    cairo,
    tripoli,
    algiers,
    constantinople,
    kherson,
    rabat, dakar, freetown,
    lagos,luanda, solala, mozambique,
    mombasu, mogadishu, aden ,bombay,
    cochin ,mangalore, colombo, madras,
    pudicherry, kuttak ,dhaka ,calcuta ,chittgong, plangki, hanthawadi
}
